# Generated by Django 3.1.2 on 2020-11-09 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderLineItems',
            new_name='OrderLineItem',
        ),
    ]
